# Generated by Django 4.1.7 on 2023-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_post_delete_custumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Foody Blog', max_length=255),
        ),
    ]
